apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: nginx-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NginxOperator is the Schema for the nginxoperators API
      displayName: Nginx Operator
      kind: NginxOperator
      name: nginxoperators.operator.example.com
      version: v1alpha2
    - description: NginxOperator is the Schema for the nginxoperators API
      displayName: Nginx Operator
      kind: NginxOperator
      name: nginxoperators.operator.example.com
      version: v1alpha1
  description: Operator for managing a basic Nginx deployment
  displayName: Nginx Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nginx
  - tutorial
  links:
  - name: Nginx Operator
    url: https://nginx-operator.domain
  maintainers:
  - email: mike@mycompany.example
    name: Mike Dame
  maturity: alpha
  provider:
    name: MyCompany
    url: http://mycompany.example
  replaces: nginx-operator.v0.0.1
  version: 0.0.0
